from __future__ import annotations

import random

from skyjo2 import HAND_ROWS, Finger, Game, GameState, Player


class TestGame:
    def test_new(self) -> None:
        game = Game.new(players=2)
        assert game == Game(
            state=GameState.DEAL_FIRST_CARDS,
            turn_index=0,
            draw_pile=(5, 10, 15, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=None,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                        Finger(card_index=None, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )

    def test_with_deal(self) -> None:
        game = Game.new(players=2)
        game = game.with_discard_and_first_cards_dealt((0, 1, 2))
        assert game == Game(
            state=GameState.REVEAL_SECOND_CARD,
            turn_index=0,
            draw_pile=(
                5 - 1,
                10 - 1,
                15 - 1,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )

    def test_with_random_deal(self, rng: random.Random) -> None:
        game = Game.new(players=2)
        game = game.with_random_discard_and_first_cards_dealt(rng)
        assert game == Game(
            state=GameState.REVEAL_SECOND_CARD,
            turn_index=0,
            draw_pile=(5, 9, 15, 10, 10, 10, 10, 10, 10, 9, 9, 10, 10, 10, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=9,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )

    def test_with_second_card_revealed(self, rng: random.Random) -> None:
        game = Game.new(players=2)
        game = game.with_random_discard_and_first_cards_dealt(rng)
        game = game.with_random_second_card_revealed(1, rng)
        assert game == Game(
            state=GameState.REVEAL_SECOND_CARD,
            turn_index=1,
            draw_pile=(5, 9, 15, 10, 10, 10, 9, 10, 10, 9, 9, 10, 10, 10, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=9,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )
        game = game.with_random_second_card_revealed(HAND_ROWS, rng)
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=0,
            draw_pile=(5, 9, 15, 10, 10, 10, 9, 10, 10, 9, 9, 10, 10, 9, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=9,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )

    def test_with_draw_discarded_and_card_revealed(self, rng: random.Random) -> None:
        game = Game.new(players=2)
        game = game.with_random_discard_and_first_cards_dealt(rng)
        game = game.with_random_second_card_revealed(1, rng)
        game = game.with_random_second_card_revealed(HAND_ROWS, rng)
        game = game.with_random_drawn_card(rng)
        game = game.with_draw_discarded_and_random_card_revealed(2, rng)
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=1,
            draw_pile=(5, 9, 15, 10, 10, 10, 9, 10, 10, 9, 8, 10, 9, 9, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0),
            discarded_card_index=12,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )

    def test_with_draw_discarded_and_card_revealed_clear(self) -> None:
        game = Game.new(players=2)
        game = game.with_discard_and_first_cards_dealt((0, 1, 2))
        game = game.with_second_card_revealed(1, 1)  # player 1
        game = game.with_second_card_revealed(1, 2)  # player 2
        game = game.with_card_drawn(0)  # player 1
        game = game.with_draw_discarded_and_card_revealed(2, 1)  # player 1
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=1,
            draw_pile=(3, 7, 13, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10),
            drawn_card_index=None,
            discard_pile=(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=1,
            end_player_index=None,
        )

    def test_with_draw_discarded_and_card_revealed_end(self) -> None:
        game = Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=99,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 1,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )
        game = game.with_card_drawn(0)
        game = game.with_draw_discarded_and_card_revealed(11, 12)
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=100,
            draw_pile=(
                5 - 2,
                10 - 1,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=1,
        )
        game = game.with_card_drawn(0)
        game = game.with_draw_discarded_and_card_revealed(11, 1)
        assert game == Game(
            state=GameState.REVEAL_HIDDEN_CARDS,
            turn_index=101,
            draw_pile=(
                5 - 3,
                10 - 2,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=1,
        )

    def test_with_card_replaced_with_draw(self, rng: random.Random) -> None:
        game = Game.new(players=2)
        game = game.with_random_discard_and_first_cards_dealt(rng)
        game = game.with_random_second_card_revealed(1, rng)
        game = game.with_random_second_card_revealed(HAND_ROWS, rng)
        game = game.with_random_drawn_card(rng)
        game = game.with_random_card_replaced_with_draw(1, rng)
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=1,
            draw_pile=(5, 9, 15, 10, 10, 10, 9, 10, 10, 9, 9, 10, 9, 9, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0),
            discarded_card_index=6,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )

    def test_with_card_replaced_with_draw_clear(self) -> None:
        game = Game.new(players=2)
        game = game.with_discard_and_first_cards_dealt((0, 1, 2))
        game = game.with_second_card_revealed(1, 1)  # player 1
        game = game.with_second_card_revealed(1, 2)  # player 2
        game = game.with_card_drawn(1)  # player 1
        game = game.with_card_replaced_with_draw(2, 0)  # player 1
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=1,
            draw_pile=(3, 7, 13, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10),
            drawn_card_index=None,
            discard_pile=(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=1,
            end_player_index=None,
        )

    def test_with_card_replaced_with_draw_end(self) -> None:
        game = Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=99,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 1,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )
        game = game.with_card_drawn(12)
        game = game.with_card_replaced_with_draw(11, 0)
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=100,
            draw_pile=(
                5 - 2,
                10 - 1,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=1,
        )
        game = game.with_card_drawn(1)
        game = game.with_card_replaced_with_draw(11, 0)
        assert game == Game(
            state=GameState.REVEAL_HIDDEN_CARDS,
            turn_index=101,
            draw_pile=(
                5 - 3,
                10 - 2,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=1,
        )

    def test_with_card_replaced_with_discard(self, rng: random.Random) -> None:
        game = Game.new(players=2)
        game = game.with_random_discard_and_first_cards_dealt(rng)
        game = game.with_random_second_card_revealed(1, rng)
        game = game.with_random_second_card_revealed(HAND_ROWS, rng)
        game = game.with_random_card_replaced_with_discard(1, rng)
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=1,
            draw_pile=(5, 9, 15, 10, 10, 10, 9, 10, 10, 9, 9, 10, 10, 9, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=6,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )

    def test_with_card_replaced_with_discard_clear(self, rng: random.Random) -> None:
        game = Game.new(players=2)
        game = game.with_discard_and_first_cards_dealt((1, 1, 2))
        game = game.with_second_card_revealed(1, 1)  # player 1
        game = game.with_second_card_revealed(1, 2)  # player 2
        game = game.with_card_replaced_with_discard(2, 0)  # player 1
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=1,
            draw_pile=(4, 7, 13, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=1,
            end_player_index=None,
        )

    def test_with_card_replaced_with_discard_end(self) -> None:
        game = Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=99,
            draw_pile=(
                5,
                10 - 2,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 1,  # initial discard
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=1,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=None,
        )
        game = game.with_card_replaced_with_discard(11, 12)
        assert game == Game(
            state=GameState.DRAW_OR_REPLACE_WITH_DISCARD,
            turn_index=100,
            draw_pile=(
                5,
                10 - 2,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=12,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=1,
        )
        game = game.with_card_replaced_with_discard(11, 0)
        assert game == Game(
            state=GameState.REVEAL_HIDDEN_CARDS,
            turn_index=101,
            draw_pile=(
                5 - 1,
                10 - 2,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=1,
        )

    def test_with_hidden_cards_revealed_tie(self) -> None:
        game = Game(
            state=GameState.REVEAL_HIDDEN_CARDS,
            turn_index=100,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )
        game = game.with_hidden_cards_revealed((11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1))
        assert game == Game(
            state=GameState.DEAL_FIRST_CARDS,
            turn_index=100,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 2,
                15 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=108,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=54,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )

    def test_with_hidden_cards_revealed_lose(self) -> None:
        game = Game(
            state=GameState.REVEAL_HIDDEN_CARDS,
            turn_index=100,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 2,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )
        game = game.with_hidden_cards_revealed((2,) * 11)
        assert game == Game(
            state=GameState.DEAL_FIRST_CARDS,
            turn_index=100,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 13,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=108,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )

    def test_with_hidden_cards_revealed_win(self) -> None:
        game = Game(
            state=GameState.REVEAL_HIDDEN_CARDS,
            turn_index=100,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10,
                10 - 1,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )
        game = game.with_hidden_cards_revealed((14,) * 5 + (13,) * 6)
        assert game == Game(
            state=GameState.DEAL_FIRST_CARDS,
            turn_index=100,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 6,
                10 - 6,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=54,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=138,
                    hand=(
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=13, is_revealed=True),
                        Finger(card_index=13, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )

    def test_with_random_hidden_cards_revealed(self, rng: random.Random) -> None:
        game = Game(
            state=GameState.REVEAL_HIDDEN_CARDS,
            turn_index=100,
            draw_pile=(
                5 - 1,  # initial discard
                10 - 1,
                15 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 1,
                10 - 2,
                10,
                10,
            ),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=0,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                        Finger(card_index=None, is_revealed=False),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )
        game = game.with_random_hidden_cards_revealed(rng)
        assert game == Game(
            state=GameState.DEAL_FIRST_CARDS,
            turn_index=100,
            draw_pile=(4, 8, 14, 9, 9, 8, 9, 8, 7, 9, 8, 8, 7, 10, 7),
            drawn_card_index=None,
            discard_pile=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            discarded_card_index=0,
            players=(
                Player(
                    score=54,
                    hand=(
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=2, is_revealed=True),
                        Finger(card_index=3, is_revealed=True),
                        Finger(card_index=4, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=6, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=9, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                    ),
                ),
                Player(
                    score=92,
                    hand=(
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=10, is_revealed=True),
                        Finger(card_index=12, is_revealed=True),
                        Finger(card_index=1, is_revealed=True),
                        Finger(card_index=7, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=11, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                        Finger(card_index=14, is_revealed=True),
                        Finger(card_index=5, is_revealed=True),
                        Finger(card_index=8, is_revealed=True),
                    ),
                ),
            ),
            start_player_index=0,
            end_player_index=0,
        )
