import dataclasses
import pathlib
import pickle
import typing

import numpy as np

from . import config
from . import play
from . import game as sj
from . import skynet
from . import train_utils


@dataclasses.dataclass(frozen=True, slots=True)
class TargetShapeSpec:
    name: str
    shape: tuple[int, ...]


TargetSpecs: typing.TypeAlias = tuple[TargetShapeSpec, ...]
TargetSpecInput: typing.TypeAlias = (
    TargetSpecs | list[TargetShapeSpec | dict[str, typing.Any]] | None
)


def core_target_specs(
    players: int,
    action_mask_shape: tuple[int, ...],
) -> TargetSpecs:
    return (
        TargetShapeSpec(
            name=train_utils.VALUE_TARGET_NAME,
            shape=(players,),
        ),
        TargetShapeSpec(
            name=train_utils.POLICY_TARGET_NAME,
            shape=action_mask_shape,
        ),
    )


def default_target_specs(
    spatial_input_shape: tuple[int, ...],
    action_mask_shape: tuple[int, ...],
) -> TargetSpecs:
    assert len(spatial_input_shape) > 0, (
        "spatial_input_shape must include the player dimension"
    )
    return core_target_specs(
        players=spatial_input_shape[0],
        action_mask_shape=action_mask_shape,
    )


def resolve_target_specs(
    target_specs: TargetSpecInput,
    *,
    spatial_input_shape: tuple[int, ...],
    action_mask_shape: tuple[int, ...],
) -> TargetSpecs:
    if target_specs is None:
        return default_target_specs(spatial_input_shape, action_mask_shape)
    return tuple(
        spec if isinstance(spec, TargetShapeSpec) else TargetShapeSpec(**spec)
        for spec in target_specs
    )


@dataclasses.dataclass(slots=True)
class Config(config.Config):
    max_size: int
    spatial_input_shape: tuple[int, ...]
    non_spatial_input_shape: tuple[int, ...]
    action_mask_shape: tuple[int, ...]
    target_specs: TargetSpecs | None = None
    path: pathlib.Path | None = None


class ReplayBuffer:
    """A replay buffer to hold the experience generated by the played games.

        Each element in the buffer is a list of training data points generated
    from a single game. Once the buffer is full, the oldest game is discarded.

        Sampling from the buffer returns a random batch of training data points
    from across all games.
    """

    def __init__(
        self,
        max_size: int,
        spatial_input_shape: tuple[int, ...],
        non_spatial_input_shape: tuple[int, ...],
        action_mask_shape: tuple[int, ...],
        target_specs: TargetSpecInput = None,
        path: pathlib.Path | None = None,
    ):
        self.max_size = max_size
        self.target_specs = resolve_target_specs(
            target_specs,
            spatial_input_shape=spatial_input_shape,
            action_mask_shape=action_mask_shape,
        )
        self.target_names = tuple(spec.name for spec in self.target_specs)
        self.game_states = [None] * max_size
        self.spatial_input_buffer = np.empty(
            (max_size, *spatial_input_shape), dtype=np.float32
        )
        self.non_spatial_input_buffer = np.empty(
            (max_size, *non_spatial_input_shape), dtype=np.float32
        )
        self.action_masks = np.empty((max_size, *action_mask_shape), dtype=np.float32)
        self.target_buffers = {
            spec.name: np.empty((max_size, *spec.shape), dtype=np.float32)
            for spec in self.target_specs
        }
        self.count = 0
        self.path = path

    @classmethod
    def from_config(cls, config: Config) -> typing.Self:
        return cls(
            config.max_size,
            config.spatial_input_shape,
            config.non_spatial_input_shape,
            config.action_mask_shape,
            config.target_specs,
            config.path,
        )

    @classmethod
    def load(cls, path: pathlib.Path) -> typing.Self:
        with open(path, "rb") as f:
            return pickle.load(f)

    def __len__(self):
        return min(self.count, self.max_size)

    def add(
        self,
        game_state: sj.Skyjo,
        targets: typing.Any,
    ):
        buffer_index = self.count
        if self.count >= self.max_size:
            buffer_index = self.count % self.max_size
        normalized_targets = train_utils.normalize_numpy_targets(
            targets, self.target_names
        )
        self.game_states[buffer_index] = game_state
        self.spatial_input_buffer[buffer_index] = skynet.get_spatial_state_numpy(
            game_state
        )
        self.non_spatial_input_buffer[buffer_index] = (
            skynet.get_non_spatial_state_numpy(game_state)
        )
        self.action_masks[buffer_index] = sj.actions(game_state).astype(np.float32)
        for name, target_buffer in self.target_buffers.items():
            target_value = normalized_targets.get(name)
            assert target_value is not None, f"expected target {name} to be present"
            target_buffer[buffer_index] = target_value
        self.count += 1

    def add_game_data(self, game_data: play.GameData):
        """Adds a game's worth of training data to the buffer."""

        for data_point in game_data:
            self.add(data_point.state, data_point.targets)

    def sample_element(self) -> train_utils.TrainingDataPoint:
        assert (
            len(self.spatial_input_buffer)
            == len(self.non_spatial_input_buffer)
            == len(self.action_masks)
        ), "All buffers must be the same length"
        for target_buffer in self.target_buffers.values():
            assert len(self.spatial_input_buffer) == len(target_buffer), (
                "All buffers must be the same length"
            )
        assert len(self) > 0, "Buffer is empty"
        # Select a random index first
        index = np.random.randint(len(self.spatial_input_buffer))
        return train_utils.TrainingDataPoint(
            self.spatial_input_buffer[index],
            self.non_spatial_input_buffer[index],
            self.action_masks[index],
            {name: target_buffer[index] for name, target_buffer in self.target_buffers.items()},
        )

    def sample_batch(self, batch_size: int) -> train_utils.TrainingBatch:
        assert (
            len(self.spatial_input_buffer)
            == len(self.non_spatial_input_buffer)
            == len(self.action_masks)
        ), "All buffers must be the same length"
        for target_buffer in self.target_buffers.values():
            assert len(self.spatial_input_buffer) == len(target_buffer), (
                "All buffers must be the same length"
            )
        assert len(self) > 0, "Buffer is empty"
        assert batch_size <= len(self), (
            f"Batch size {batch_size} cannot be larger than buffer size {len(self)} when sampling without replacement."
        )
        indices = np.random.choice(
            len(self), size=batch_size
        )  # replace=False is VERY slow
        # Retrieve elements using the sampled indices
        batch = train_utils.TrainingBatch(
            self.spatial_input_buffer[indices],
            self.non_spatial_input_buffer[indices],
            self.action_masks[indices],
            {
                name: target_buffer[indices]
                for name, target_buffer in self.target_buffers.items()
            },
        )
        return batch

    def generate_training_batches(
        self, batch_size: int, batch_count: int
    ) -> typing.Generator[train_utils.TrainingBatch, None, None]:
        for _ in range(batch_count):
            yield self.sample_batch(batch_size)

    def save(self, path: pathlib.Path | None = None) -> pathlib.Path:
        if path is None:
            path = self.path

        assert path is not None, (
            "If path is not provided, it must be provided during initialization"
        )
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "wb") as f:
            pickle.dump(self, f)
        return path
